// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  const Assets._();
  static const String assets_candychef_zmtzawqlp_candies =
      'assets/CandyChef/zmtzawqlp/candies';

  static const String assets_flare_bottomslime_flr =
      'assets/flare/bottomSlime.flr';

  static const String assets_flare_topslime_flr = 'assets/flare/topSlime.flr';

  static const String assets_images_flutter_candies_logo_png =
      'assets/images/flutter_candies_logo.png';
}
