const Map<String, List<String>> candyConsts = <String, List<String>>{
  'zmtzawqlp': <String>[
    'assets/CandyChef/zmtzawqlp/candies.md',
    'assets/CandyChef/zmtzawqlp/PullPush/2.Flutter 轻松构建加载更多(loading more).md',
    'assets/CandyChef/zmtzawqlp/PullPush/1.Flutter 下拉刷新花式玩法.md',
    'assets/CandyChef/zmtzawqlp/Tools/2.Flutter JsonToDart Mac版 lei了，真的不mark吗.md',
    'assets/CandyChef/zmtzawqlp/Tools/4.Flutter 法法路由注解.md',
    'assets/CandyChef/zmtzawqlp/Tools/6.Flutter 法法注解路由 4.0.md',
    'assets/CandyChef/zmtzawqlp/Tools/3.Flutter JsonToDart 工具.md',
    'assets/CandyChef/zmtzawqlp/Tools/5.Flutter 法法注解路由 2.0.md',
    'assets/CandyChef/zmtzawqlp/Tools/1.Flutter 功能最全的JsonToDart工具(桌面Web海陆空支持).md',
    'assets/CandyChef/zmtzawqlp/Sliver/1.Flutter Sliver一生之敌 (ScrollView).md',
    'assets/CandyChef/zmtzawqlp/Sliver/4.Flutter Sliver 锁住你的美.md',
    'assets/CandyChef/zmtzawqlp/Sliver/3.Flutter Sliver你要的瀑布流小姐姐.md',
    'assets/CandyChef/zmtzawqlp/Sliver/2.Flutter Sliver一生之敌 (ExtendedList).md',
    'assets/CandyChef/zmtzawqlp/Web/1.Flutter for web 最新填坑.md',
    'assets/CandyChef/zmtzawqlp/Web/2.Flutter Candies for web.md',
    'assets/CandyChef/zmtzawqlp/TextField/3.Flutter 自定义输入框Selection菜单和选择器.md',
    'assets/CandyChef/zmtzawqlp/TextField/2.Flutter 支持图片以及特殊文字的输入框（二）实现过程.md',
    'assets/CandyChef/zmtzawqlp/TextField/1.Flutter 支持图片以及特殊文字的输入框（一）使用方法.md',
    'assets/CandyChef/zmtzawqlp/Desktop/1.Flutter go flutter desktop 填坑.md',
    'assets/CandyChef/zmtzawqlp/Desktop/2.Dart Pub Global 创建命令行应用程序（Windows).md',
    'assets/CandyChef/zmtzawqlp/Image/4.Flutter 图片裁剪旋转翻转编辑器.md',
    'assets/CandyChef/zmtzawqlp/Image/3.Flutter 仿掘金微信图片滑动退出页面效果.md',
    'assets/CandyChef/zmtzawqlp/Image/1.Flutter 什么功能都有的Image.md',
    'assets/CandyChef/zmtzawqlp/Image/5.Flutter 图片全家桶.md',
    'assets/CandyChef/zmtzawqlp/Image/2.Flutter 可以缩放拖拽的图片.md',
    'assets/CandyChef/zmtzawqlp/zmtzawqlp.md',
    'assets/CandyChef/zmtzawqlp/SDK/2.Flutter Analysis Options.md',
    'assets/CandyChef/zmtzawqlp/SDK/1.Flutter v1.12.13 的一些坑.md',
    'assets/CandyChef/zmtzawqlp/GettingStarted/2.Flutter widgets Container Row Column Image.md',
    'assets/CandyChef/zmtzawqlp/GettingStarted/5.Flutter 你想知道的Widget可视区域,相对位置,大小.md',
    'assets/CandyChef/zmtzawqlp/GettingStarted/1.Flutter 入门安装——C#程序喵的Flutter之旅.md',
    'assets/CandyChef/zmtzawqlp/GettingStarted/4.Flutter 萌新高频问题(加班猿妈妈叫你回家吃饭了).md',
    'assets/CandyChef/zmtzawqlp/GettingStarted/3.Flutter widgets Text Icon Button.md',
    'assets/CandyChef/zmtzawqlp/Text/3.Flutter RichText支持自定义文字背景.md',
    'assets/CandyChef/zmtzawqlp/Text/1.Flutter RichText支持图片显示和自定义图片效果.md',
    'assets/CandyChef/zmtzawqlp/Text/2.Flutter RichText支持自定义文本溢出效果.md',
    'assets/CandyChef/zmtzawqlp/Text/4.Flutter RichText支持特殊文字效果.md',
    'assets/CandyChef/zmtzawqlp/Text/5.Flutter RichText支持文本选择.md',
    'assets/CandyChef/zmtzawqlp/Nested/1.Flutter 扩展NestedScrollView （一）Pinned头引起的bug解决.md',
    'assets/CandyChef/zmtzawqlp/Nested/2.Flutter 扩展NestedScrollView （二）列表滚动同步解决.md',
    'assets/CandyChef/zmtzawqlp/Nested/3.Flutter 扩展NestedScrollView （三）下拉刷新的解决.md',
    'assets/CandyChef/zmtzawqlp/Awesome/4.2019 C#程序喵的Flutter之旅.md',
    'assets/CandyChef/zmtzawqlp/Awesome/5.Flutter Candies 糖果小助手.md',
    'assets/CandyChef/zmtzawqlp/Awesome/1.Flutter 仿掘金推特点赞按钮.md',
    'assets/CandyChef/zmtzawqlp/Awesome/2.Flutter 扩展的联动Tabs.md',
    'assets/CandyChef/zmtzawqlp/Awesome/3.Flutter Candies 一桶天下.md',
  ],
};
