// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://ArticlePage',
  'fluttercandies://CandyChefPage',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'ArticlePage'
  ///
  /// [name] : 'fluttercandies://ArticlePage'
  ///
  /// [routeName] : 'ArticlePage'
  ///
  /// [constructors] :
  ///
  /// ArticlePage : [Article(required) article]
  static const String fluttercandiesArticlePage =
      'fluttercandies://ArticlePage';

  /// 'CandyChefPage'
  ///
  /// [name] : 'fluttercandies://CandyChefPage'
  ///
  /// [routeName] : 'CandyChefPage'
  ///
  /// [constructors] :
  ///
  /// CandyChefPage : [CandyChef(required) candyChef]
  static const String fluttercandiesCandyChefPage =
      'fluttercandies://CandyChefPage';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>> keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
