// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://demo1',
  'fluttercandies://demo2',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'demo1'
  ///
  /// [name] : 'fluttercandies://demo1'
  ///
  /// [routeName] : 'demo1'
  ///
  /// [description] : 'demo1'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesDemo1 = 'fluttercandies://demo1';

  /// 'demo2'
  ///
  /// [name] : 'fluttercandies://demo2'
  ///
  /// [routeName] : 'demo2'
  ///
  /// [description] : 'demo2'
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesDemo2 = 'fluttercandies://demo2';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [arguments] : [keyValue]
  ///
  /// [argumentTypes] : [List<DemoRouteResult>]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
